### ISSUE TITLE
npm installing purescript requires node v6

### ISSUE THREAD

**Issue by felixSchl** [purescript-contrib/node-purescript-bin#44]
I feel like this requirement should be lifted as output from the purescript compiler runs fine on versions of node all the way back to 0.12 and probably earlier. I think the convenience of the developer using ES6 features in the install script should come second to the impact it has for downstream users installing purescript. In particular, [this](https://github.com/purescript-contrib/node-purescript-bin/blob/40116bf4c7540229d7c866f909f738ef4aba3168/lib/install.js#L9) is causing the requirement for node 6.

Edit: I'd be willing to volunteer the time if this was to be accepted in a PR

**Comment by shinnn** [comment]
Node.js < 6 is no longer actively maintained.

**Comment by felixSchl** [comment]
I am sorry, but this is simply [not true](https://github.com/nodejs/LTS). Node 4.x is still maintained until April 2018. There is very little involved to have this install on node 4, or even on old (unmaintained) legacy versions of node. I think this tool should install on any version that purescript  output runs on. Again, I am happy to make this contribution if such a contribution would be accepted.

**Comment by shinnn** [comment]
> I am sorry

No problem.

> this is simply not true.

Simply true. Again, Node.js < 6 is no longer *actively* maintained.

> I am happy to make this contribution if such a contribution would be accepted.

Not needed. Just upgrade Node.js. A new even-numbered major version v8.0.0 will be released soon and there is no reason to use the too outdated one.

**Comment by felixSchl** [comment]
Alright, so it's not been _actively_ maintained for nearly 3 weeks now, but it's still being maintained as part of the LTS. But I won't get hung up fighting that strawman - the bottom line is that you expect every downstream developer to update their version of node, simply so a tool that merely installs another package (which, as it turns out, runs on _any_ version of node) can run it's 40 line install script. I just do not understand why, there's virtually **no cost** at all to support older versions of node.

**Comment by shinnn** [comment]
Yes, this package *merely* installs `purs` binary, but please imagine how many tasks this package should perform:

* Download a tgz archive of the prebuilt binary from Github
* Extract the archive
* Verify the downloaded `purs` binary works correctly
* If the prebuilt binary doesn't work in your environment switch to the fallback:
  * Download a tgz archive of the PureScript source
  * Extract the archive
  * Built a binary with `stack` command
* Perform all the tasks above cross-platform

I've developed [`download`](https://github.com/kevva/download), [`decompress`](https://github.com/kevva/decompress) and [its plugins](https://www.npmjs.com/browse/keyword/decompressplugin) with Kevin for years, in order to accomplish what you call *merely an installation*.

> I think the convenience of the developer using ES6 features in the install script should come second to the impact it has for downstream users installing purescript.

>  there's virtually no cost at all to support older versions of node.

You tend to underestimate the maintenance cost of this module, but it's not just a 40-line script as you think. Reducing maintenance cost is more important than currying favor with lazy developers who don't know how to update the software. Dropping Node < 6 support helps a lot with maintaining a Node.js package — its author can use convenient ES2016+ syntax and choose the dependencies [without Node =< 4 support](https://github.com/sindresorhus/array-differ/commit/9a2f73fcdc8200781ae33aea1038600faa48513f) in the future.

> I won't get hung up fighting that strawman

Me too.

**Comment by felixSchl** [comment]
Well, there is competition now: https://github.com/felixSchl/node-purescript. An alternative that is written in purescript and does not arbitrarily require the latest and greatest version of node. I also chose to narrow the scope to not do builds from sources at the moment, plus I am using only few dependencies that do most of the magic: create a download stream with `request`, pipe it into `gunzip-maybe` and pipe that into `tar-fs`, so I never even have to write the tar ball to disk, unless we want to add a disk based caching layer later or something.

**Comment by shinnn** [comment]
First, don't publish the npm package with `node-` prefix, which violates the package name convention. https://docs.npmjs.com/files/package.json#name

> I am using only few dependencies that do most of the magic: create a download stream with request, pipe it into gunzip-maybe and pipe that into tar-fs

Yes, yes, using `request` is a common mistake for creating this kind of module.

```
time npm i request

real	0m8.347s
user	0m3.907s
sys	0m0.743s

du -s node_modules
13728	node_modules
```

```
time npm i got

real	0m3.194s
user	0m1.535s
sys	0m0.240s

616	node_modules
```

> I never even have to write the tar ball to disk

This module also does too.

> there is competition now

> I also chose to narrow the scope to not do builds from sources at the moment

How competitive. Good luck!

**Comment by felixSchl** [comment]
Thank you for your valuable feedback, I'll make those updates - very interesting notes about the request module indeed :-) Trust me when I say I did not want to that module name... I think we can leave things here, if not competition it at least does what I need it to for my purposes.
